### ISSUE TITLE
Failed to get certificate URL

### ISSUE THREAD

**Issue by nikhilmutkekar** [Azure/packer-azure#262] opened 2016-08-22 14:05 UTC
Getting the certificate's URL ...
  -> Key Vault Name        : 'pkrkv****l8x9'
  -> Key Vault Secret Name : 'packerKeyVaultSecret'
  ...failed to get certificate URL, retry(0)
  ...failed to get certificate URL, retry(1)
  ...failed to get certificate URL, retry(2)
  ...failed to get certificate URL, retry(3)
  ...failed to get certificate URL, retry(4)

 Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go value of type string'.

Receiving this error for Azure ARM based packer build for Windows-2012-R2 SKU. Help !

**Comment by boumenot** [comment] 2016-08-22 16:25
Packer Azure ARM development occurs in the official Packer [repository][1].  Please log and review all issues from that repository.

This appears to be a duplicate of a fixed [issue][2].  Unfortunately, a new release of Packer with the fix has not been made.  You will need to rebuild master to get the fix.  I posted a private build to another dupe of this [issue][3] if that is preferable.

[1]: https://github.com/mitchellh/packer
[2]: https://github.com/mitchellh/packer/pull/3721
[3]: https://github.com/mitchellh/packer/issues/3766

**Closed by boumenot** 2016-08-22 16:25 UTC
